### ISSUE TITLE
App not grabbing author string when input as a single field in Zotero

### ISSUE THREAD

**Issue by wlpotter** [srophe/zotero2bibl#13]
Hi @wsalesky, @davidamichelson 

The app doesn't seem to work with author/editor data from Zotero that is not broken into surname and forename. For example, the author string in the record here: https://www.zotero.org/groups/392292/syriaca.org_test_bibliography_module/items/itemKey/4ELQNR8R is "Abū Jaʿfar Muḥammad Jarīr al-Ṭabarī", as a single string. The generated TEI bibl record does not grab this string, and leaves the <author> element empty.

Is there a way for the script to handle single-field author/editor data from Zotero?

**Comment by wsalesky** [comment]
@wlpotter yes. What is the preferred TEI encoding when the name is not broken up? 

`<author>Abū Jaʿfar Muḥammad Jarīr al-Ṭabarī</author>`
or
`<author><persName>Abū Jaʿfar Muḥammad Jarīr al-Ṭabarī</persName></author>`
or something else?

**Comment by davidamichelson** [comment]
Lets nest it in TEI:name please

**Comment by davidamichelson** [comment]
Examples:
```
<author><name>Abū Jaʿfar Muḥammad Jarīr al-Ṭabarī</name></author>
```

**Comment by wsalesky** [comment]
Fixed.
