### ISSUE TITLE
[Question] Juris-m compatibility

### ISSUE THREAD

**Issue by duncdrum** [srophe/zotero2bibl#3]
Would you be interested in extending the functionally towards [juris-m](https://juris-m.github.io) (the artist formerly known as multi-lingual Zotero). This would require parsing the extras field in addition to the standard Zotero tei output. 

Things are still somewhat in flux around the Zotero 5 conversion, but I'm happy to help if it is something you are interested in.

**Comment by wsalesky** [comment]
@duncdrum I'm not sure that is in the scope of our initial project specs, but we will be interested in extending the functionality to parse extra fields that are not included in the standard Zotero tei output as our next step. 

I will keep you in the loop as our project scope develops. Thanks for the offer of help.
